# Using the bullseye image due to
# compatibility with opam 2.0.8-1
image: "rsngit.radiancetech.com:5005/pearls/coq-pearls"

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

cache:
  key: $CI_JOB_NAME
  paths:
    - .cache/pip

stages:
  - test

before_script:
  - apt-get -y update
  - apt-get -y install pkg-config make strace
  - apt-get -y install time
  - source /var/venv/bin/activate
  - export VENV=/var/venv
  - make install

precommit:
  interruptible: true
  stage: test
  before_script:
    # Global before_script does not get prepended
    # Track https://gitlab.com/gitlab-org/gitlab/-/issues/258606
    - source /var/venv/bin/activate
    - which ssh-agent || apt-get install openssh-client -qqy
    - eval `ssh-agent -s`
    - echo "${PRECOMMIT_CI_PRIVATE_KEY}" | base64 -d | ssh-add - > /dev/null # add ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - pip install pre-commit
    - pre-commit install
    - precommit_passed=0
    - git fetch --force origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}:${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - pre-commit run --files $(git diff-tree --no-commit-id --name-only -r HEAD origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}) || precommit_passed=$?
    - if (( $precommit_passed == 0 )) ; then echo "All pre-commit checks passed"; exit 0; fi
    - files_changes=0
    - test "$(git status -uno -s)" != "" || files_changed=$?
    - if (( $files_changed != 0 )) ; then echo "Some pre-commit checks failed"; exit 1; fi
    - git add -u
    - git config --global user.email "${PRECOMMIT_CI_EMAIL}"
    - git config --global user.name "${PRECOMMIT_CI_USERNAME}"
    - git commit -m "[pre-commit-ci] Apply pre-commit hooks." --no-verify
    - git remote set-url origin ssh://git@${CI_SERVER_HOST}:${CI_SERVER_SSH_PORT}/${CI_PROJECT_PATH}.git
    - git push origin HEAD:${CI_COMMIT_REF_NAME}
    - echo "Some pre-commit checks altered files. Fixes pushed as new commit."
    - exit 1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.runTests:
  interruptible: true
  stage: test
  script:
    - eval $(opam env)
    - make test_${COQ_VERSION}
  artifacts:
    expose_as: 'test logs'
    paths: ['test_logs/']
    expire_in: 1 week

runTestsUnmarked:
  extends: .runTests
  variables:
    COQ_VERSION: "none"

runTests_8_9_1:
  extends: .runTests
  variables:
    COQ_VERSION: "8_9_1"

runTests_8_10_2:
  extends: .runTests
  variables:
    COQ_VERSION: "8_10_2"

runTests_8_11_2:
  extends: .runTests
  variables:
    COQ_VERSION: "8_11_2"

runTests_8_12_2:
  extends: .runTests
  variables:
    COQ_VERSION: "8_12_2"

runTests_8_13_2:
  extends: .runTests
  variables:
    COQ_VERSION: "8_13_2"

runTests_8_14_1:
  extends: .runTests
  variables:
    COQ_VERSION: "8_14_1"

runTests_8_15_2:
  extends: .runTests
  variables:
    COQ_VERSION: "8_15_2"
