repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: c6077954245bc3add82dafd853a1c7305a6ebd20
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [-i,
               --wrap-summaries,
               '72',
               --wrap-descriptions,
               '72',
               --tab_width,
               '4',
               --make-summary-multi-line,
               --pre-summary-newline]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==20.11.1',
          'flake8-docstrings==1.5.0'
        ]
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
