repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: d3873c0693fe08e6233177c2f342af62547dcaa6
    hooks:
      - id: yapf
        additional_dependencies: [toml, tomli]
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [-i,
               --wrap-summaries,
               '72',
               --wrap-descriptions,
               '72',
               --tab_width,
               '4',
               --make-summary-multi-line,
               --pre-summary-newline]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==23.1.20',
          'flake8-docstrings==1.7.0'
        ]
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
  # Clear notebook metadata
  - repo: https://github.com/datarootsio/databooks
    rev: 1.3.7
    hooks:
      - id: databooks-meta
  # Clear notebook outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  # Notebook formatting, linting, etc.
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-flake8
      - id: nbqa-isort
      - id: nbqa-yapf
